#pragma once

/**
 * @file lamp_scan.h
 * @author Jefferson J. Hunt (jefferson@oneoffendeavors.com)
 * @brief Chained '161 + dual '251 lamp-channel scan driver (SPI + DMA).
 * @version 0.3.0
 * @date 2026-08-03
 *
 * @copyright Copyright (c) 2024-2026 Jefferson J. Hunt (MIT)
 *
 * Modules are identical and unaddressed. Each drives a '161 counter whose
 * Q0..Q2 select the channel on two tri-state '251 muxes (Q3 bank-selects), and
 * forwards the clock downstream only once its own 16 lines are done
 * (`CLK_OUT = CLK_IN AND DONE`). The clock is therefore the token, and the
 * master reads the whole chain by issuing `num_modules * channels_per_module`
 * clocks and sampling the shared `DATA` line once per clock.
 *
 * The burst is generated by the SPI peripheral (`SCLK` = `CLK`, `MISO` =
 * `DATA`), not by a software loop. That is a correctness requirement, not an
 * optimization: a production module holds its bus grant on an RC activity
 * detector, and a stall of more than a few microseconds mid-frame silently
 * resets every counter in the chain. See docs/CHAINING.md and docs/TIMING.md.
 *
 * @par SPI mode (measured, not assumed)
 * The sample must land in the middle of a line's data window, never on the edge
 * that advances the counter.
 *
 * Production modules Schmitt-invert the incoming clock, so the '161 counts on
 * the FALLING edge and line n is valid from fall(n) to fall(n+1). **Mode 0**
 * (`CPOL=0, CPHA=0`) samples on rising edges — the midpoint of that window.
 *
 * Mode 1 samples on the falling edge, i.e. exactly on the counter transition,
 * and is wrong for this hardware.
 *
 * Bench rigs that clock the '161 directly cannot be aligned by any mode: the
 * counter advances on the same rising edges SPI samples, so every sample reads
 * line[k+1] and line 0 is unreachable. Measured on an S3 + '161 + '151 rig:
 * modes 0 and 1 both produced a one-channel shift. Add an inverter in the CLK
 * path to make such a rig edge-compatible with production.
 *
 * @par Frame reset
 * Production modules reset on a clock-idle timeout, so `mr_pin` is left
 * unconfigured and the gap between transactions does the work. Bench rigs
 * without an activity detector set `mr_pin`, and the driver pulses it before
 * each frame.
 */

#include <cstddef>
#include <cstdint>

#include "driver/gpio.h"
#include "driver/spi_master.h"
#include "esp_err.h"

namespace ooe::pinled
{
    static constexpr size_t LAMPSCAN_MAX_MODULES = 8;

    struct LampScanConfig
    {
        gpio_num_t clk_pin{GPIO_NUM_NC};  ///< chain `CLK`, driven as SPI `SCLK`
        gpio_num_t data_pin{GPIO_NUM_NC}; ///< shared `DATA` bus, read as SPI `MISO`
        gpio_num_t mr_pin{GPIO_NUM_NC};   ///< optional '161 async clear; bench rigs only

        spi_host_device_t spi_host{SPI2_HOST};
        int spi_hz{2 * 1000 * 1000}; ///< chain clock; see docs/TIMING.md §4.3
        uint8_t spi_mode{0};         ///< 0 for falling-edge counters (production)

        size_t num_modules{1};          ///< modules on the chain (1..8)
        size_t channels_per_module{16}; ///< 8 (single mux) or 16 (dual '251)
        bool active_low{false};         ///< MOSFET + inverting Schmitt = non-inverting (HW-1)
    };

    class LampScan
    {
    public:
        static constexpr size_t MAX_CHANNELS = LAMPSCAN_MAX_MODULES * 16;

        esp_err_t init(const LampScanConfig &cfg);
        void deinit();

        /**
         * @brief Read one full scan frame into out[].
         *
         * One SPI transaction clocks the entire chain; channel order is
         * module-major, so out[m * channels_per_module + ch].
         *
         * @param out  caller buffer of booleans (already polarity-corrected)
         * @param n    capacity of out; must be >= total_channels()
         */
        esp_err_t read_frame(bool *out, size_t n);

        size_t total_channels() const { return cfg_.num_modules * cfg_.channels_per_module; }

        /// Bits clocked per frame; always a whole number of bytes.
        size_t frame_bits() const { return total_channels(); }

        /// Pulse `/MR` low to zero the counter. No-op when `mr_pin` is unset,
        /// which is the production case — there the idle gap resets the chain.
        void reset_counter();

        /**
         * @name Bring-up helpers
         * Single-step the counter so the '161 Q outputs can be watched or
         * probed. **Bench rigs only**: a production module holds its bus grant
         * on an RC, so stopping the clock releases the bus and clears the
         * counter. Only available when a diagnostic mode is compiled in, which
         * also selects the bit-bang backend instead of SPI.
         * @{
         */
        void step_counter();                ///< one CLK pulse
        bool sample_now(size_t module = 0); ///< read `DATA` now, polarity-corrected
        /// @}

    private:
        esp_err_t init_spi();
        esp_err_t init_bitbang();

        LampScanConfig cfg_{};
        bool initialized_{false};

        spi_device_handle_t spi_{nullptr};
        bool bus_owned_{false};
        uint8_t *rx_{nullptr}; ///< DMA-capable receive buffer, frame_bits()/8 bytes
    };
} // namespace ooe::pinled
