#pragma once

/**
 * @file lamp_scan.h
 * @author Jefferson J. Hunt (jefferson@oneoffendeavors.com)
 * @brief Chained '161 + dual '251 lamp-channel scan driver (SPI + DMA).
 * @version 0.3.0
 * @date 2026-08-03
 *
 * @copyright Copyright (c) 2024-2026 Jefferson J. Hunt (MIT)
 *
 * Modules are identical and unaddressed. Each drives a '161 counter whose
 * QA..QC select the channel on two tri-state '251 muxes (QD bank-selects), and
 * forwards the clock downstream only once its own 16 lines are done
 * (`CLK_OUT = CLK_IN AND DONE`). The clock is therefore the token.
 *
 * @par The arm clock
 * A module's `ENP` is driven by its `STARTED` latch, and `ENP` is a
 * *synchronous* enable. On the first clock edge a module receives, the '161
 * samples the old `STARTED = 0` and does not count while the latch sets. So
 * each module spends its first clock arming and the next sixteen presenting
 * lines 0..15 -- which is what gives line 0 a full bit period before it is
 * sampled.
 *
 * A frame is therefore **17 clocks per module**, and every 17th sample is an
 * arm clock carrying no data. See docs/CHAINING.md.
 *
 * The burst is generated by the SPI peripheral (`SCLK` = `CLK`, `MISO` =
 * `DATA`, `CS` = `/MR`). Since rev C the chain holds no analog state, so this
 * is a throughput choice rather than a correctness requirement -- a stalled
 * frame is late, never corrupt.
 *
 * @par SPI mode (measured, not assumed)
 * The sample must land in the middle of a line's data window, never on the edge
 * that advances the counter.
 *
 * Production modules Schmitt-invert the incoming clock, so the '161 counts on
 * the FALLING edge and line n is valid from fall(n) to fall(n+1). **Mode 0**
 * (`CPOL=0, CPHA=0`) samples on rising edges — the midpoint of that window.
 *
 * Mode 1 samples on the falling edge, i.e. exactly on the counter transition,
 * and is wrong for this hardware.
 *
 * Bench rigs that clock the '161 directly cannot be aligned by any mode: the
 * counter advances on the same rising edges SPI samples, so every sample reads
 * line[k+1] and line 0 is unreachable. Measured on an S3 + '161 + '151 rig:
 * modes 0 and 1 both produced a one-channel shift. Add an inverter in the CLK
 * path to make such a rig edge-compatible with production.
 *
 * @par Frame reset
 * `/MR` is bussed to every module and asynchronously clears all counters and
 * both '109 latches. Preferably it is driven from the SPI `CS` line with
 * positive polarity, so it is low between transactions (clearing) and high
 * during (counting) with no software involvement. Set `mr_from_cs` for that;
 * otherwise the driver pulses `mr_pin` as a plain GPIO before each frame.
 */

#include <cstddef>
#include <cstdint>

#include "driver/gpio.h"
#include "driver/spi_master.h"
#include "esp_err.h"

namespace ooe::pinled
{
    static constexpr size_t LAMPSCAN_MAX_MODULES = 8;

    struct LampScanConfig
    {
        gpio_num_t clk_pin{GPIO_NUM_NC};  ///< chain `CLK`, driven as SPI `SCLK`
        gpio_num_t data_pin{GPIO_NUM_NC}; ///< shared `DATA` bus, read as SPI `MISO`
        gpio_num_t mr_pin{GPIO_NUM_NC};   ///< bussed '161 async clear (active low)
        bool mr_from_cs{true};            ///< drive /MR from SPI CS (positive polarity)
        bool arm_clock{true};             ///< module spends its first clock arming (rev C)

        spi_host_device_t spi_host{SPI2_HOST};
        int spi_hz{2 * 1000 * 1000}; ///< chain clock; see docs/TIMING.md §4.3
        uint8_t spi_mode{0};         ///< 0 for falling-edge counters (production)

        size_t num_modules{1};          ///< modules on the chain (1..8)
        size_t channels_per_module{16}; ///< 8 (single mux) or 16 (dual '251)
        bool active_low{false};         ///< MOSFET + inverting Schmitt = non-inverting (HW-1)
    };

    class LampScan
    {
    public:
        static constexpr size_t MAX_CHANNELS = LAMPSCAN_MAX_MODULES * 16;

        esp_err_t init(const LampScanConfig &cfg);
        void deinit();

        /**
         * @brief Read one full scan frame into out[].
         *
         * One SPI transaction clocks the entire chain; channel order is
         * module-major, so out[m * channels_per_module + ch].
         *
         * @param out  caller buffer of booleans (already polarity-corrected)
         * @param n    capacity of out; must be >= total_channels()
         */
        esp_err_t read_frame(bool *out, size_t n);

        size_t total_channels() const { return cfg_.num_modules * cfg_.channels_per_module; }

        /// Clocks per module: one per line, plus the arm clock on rev C
        /// hardware. A bench rig whose '161 has ENP tied high does not arm --
        /// its first clock counts -- so `arm_clock` must be cleared there or
        /// every channel shifts by one.
        size_t clocks_per_module() const
        {
            return cfg_.channels_per_module + (cfg_.arm_clock ? 1 : 0);
        }

        /// Bits clocked per frame, before rounding up to whole bytes. Surplus
        /// clocks past this are harmless -- every module is finished and
        /// tri-stated by then.
        size_t frame_bits() const { return cfg_.num_modules * clocks_per_module(); }

        /// Bytes actually clocked (frame_bits rounded up).
        size_t frame_bytes() const { return (frame_bits() + 7) / 8; }

        /// Re-open the SPI device at a new clock rate. Diagnostic use: lets a
        /// sweep find the chain's ceiling without a reflash per step. No-op on
        /// the bit-bang backend.
        esp_err_t set_clock(int hz);

        /// Clock the hardware actually produces, after divider rounding.
        int actual_hz() const { return cfg_.spi_hz; }

        /// Pulse `/MR` low to zero the counter. No-op when `mr_pin` is unset,
        /// which is the production case — there the idle gap resets the chain.
        void reset_counter();

        /**
         * @name Bring-up helpers
         * Single-step the counter so the '161 Q outputs can be watched or
         * probed. **Bench rigs only**: a production module holds its bus grant
         * on an RC, so stopping the clock releases the bus and clears the
         * counter. Only available when a diagnostic mode is compiled in, which
         * also selects the bit-bang backend instead of SPI.
         * @{
         */
        void step_counter();                ///< one CLK pulse
        bool sample_now(size_t module = 0); ///< read `DATA` now, polarity-corrected
        /// @}

    private:
        esp_err_t init_spi();
        esp_err_t init_bitbang();

        LampScanConfig cfg_{};
        bool initialized_{false};
        bool mr_is_gpio_{false}; ///< /MR driven as a plain GPIO rather than by CS

        spi_device_handle_t spi_{nullptr};
        bool bus_owned_{false};
        uint8_t *rx_{nullptr}; ///< DMA-capable receive buffer, frame_bits()/8 bytes
    };
} // namespace ooe::pinled
