#!/usr/bin/env python3
"""Convert web/api/openapi.yaml into web/api/spec.js.

Swagger UI normally fetch()es its spec, and fetch is blocked on file://
pages — which the standalone download is (FR-UI-8). Shipping the spec as a
classic script and passing it as an object makes the docs page fetch
nothing, so it works identically from the S3 bundle and from disk. Same
pattern as tools/gen_proto_js.py; the YAML stays the human-edited source,
this output is committed so a bare checkout works.
"""

import json
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "web" / "api" / "openapi.yaml"
DST = ROOT / "web" / "api" / "spec.js"

HEADER = """\
// GENERATED by tools/gen_openapi_js.py from openapi.yaml — do not edit.
// The YAML is the source; this is its JSON, made loadable from file://
// where Swagger UI's own fetch() cannot go.
"""


def main() -> int:
    spec = yaml.safe_load(SRC.read_text(encoding="utf-8"))
    DST.write_text(
        HEADER + "window.PINLED_OPENAPI = " + json.dumps(spec) + ";\n",
        encoding="utf-8",
    )
    print(f"{DST.relative_to(ROOT)}: {DST.stat().st_size} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
