#!/usr/bin/env python3
"""Wrap proto/pinled.proto into web/js/gen/proto.js.

The SPA runs from file:// (FR-UI-8), where fetch() cannot read a sibling
file, so the schema text ships inside a classic script instead. protobuf.js
parses it at runtime — one schema authority, zero generated bindings to
drift (FR-CFG-13). Re-run after any .proto change; the output is committed
so the SPA works from a bare checkout.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "proto" / "pinled.proto"
DST = ROOT / "web" / "js" / "gen" / "proto.js"

HEADER = """\
// GENERATED by tools/gen_proto_js.py from proto/pinled.proto — do not edit.
// The schema authority is the .proto; this is only its text, made loadable
// from file:// where fetch() cannot reach it.
"""


def main() -> int:
    text = SRC.read_text(encoding="utf-8")
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text(
        HEADER + "window.PINLED_PROTO = " + json.dumps(text) + ";\n",
        encoding="utf-8",
    )
    print(f"{DST.relative_to(ROOT)}: {DST.stat().st_size} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
